### ISSUE TITLE
Incorrect API key provided when passing key from arguments 

### ISSUE THREAD

**Issue by imhafeez** [morriskurz/openai_gpt3_dart_api#5]
` InvalidRequestException: Incorrect API key provided: S8hWnMhE************************************4T0m. You can find your API key at https://beta.openai.com.`

**Comment by morriskurz** [comment]
Could you describe what your problem is and how it occurred, preferably with a working code sample?

**Comment by imhafeez** [comment]
Hi @morriskurz ,
Actually while using Flutter web (as API key get exposed) I am passing API key via arguments(environment variables). So on retrieving my key it gets decoded as mentioned above and when I pass it to your gpt-3-api package it gives me `InvalidRequestException ` exception.

I know the other solution is to make a server and do all these things there.

**Comment by morriskurz** [comment]
I am sorry that I can't be of any help to you, but this seems to be a problem with setting your environment variables correctly and passing them to the DART arguments. It is not a problem with the package in my opinion.

**Comment by morriskurz** [comment]
I am going to close this issue - if you are disagreeing of seeing more problems, don't hesitate to open a new one!
